// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Channel1 = NULL;
lv_obj_t * ui_LabelCh1 = NULL;
lv_obj_t * ui_Channel2 = NULL;
lv_obj_t * ui_LabelCh2 = NULL;
lv_obj_t * ui_Channel3 = NULL;
lv_obj_t * ui_LabelCh3 = NULL;
lv_obj_t * ui_Channel4 = NULL;
lv_obj_t * ui_LabelCh4 = NULL;
lv_obj_t * ui_Channel5 = NULL;
lv_obj_t * ui_LabelCh5 = NULL;
lv_obj_t * ui_Channel6 = NULL;
lv_obj_t * ui_LabelCh6 = NULL;
lv_obj_t * ui_Volume = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x4ADFF3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Channel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Channel1, 50);
    lv_obj_set_height(ui_Channel1, 50);
    lv_obj_set_x(ui_Channel1, 5);
    lv_obj_set_y(ui_Channel1, 18);
    lv_obj_add_state(ui_Channel1, LV_STATE_FOCUSED);       /// States
    lv_obj_clear_flag(ui_Channel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCh1 = lv_label_create(ui_Channel1);
    lv_obj_set_width(ui_LabelCh1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCh1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCh1, 0);
    lv_obj_set_y(ui_LabelCh1, -10);
    lv_obj_set_align(ui_LabelCh1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCh1, "Ch. 1");

    ui_Channel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Channel2, 50);
    lv_obj_set_height(ui_Channel2, 50);
    lv_obj_set_x(ui_Channel2, 55);
    lv_obj_set_y(ui_Channel2, 18);
    lv_obj_clear_flag(ui_Channel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCh2 = lv_label_create(ui_Channel2);
    lv_obj_set_width(ui_LabelCh2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCh2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCh2, 0);
    lv_obj_set_y(ui_LabelCh2, -10);
    lv_obj_set_align(ui_LabelCh2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCh2, "Ch.2");

    ui_Channel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Channel3, 50);
    lv_obj_set_height(ui_Channel3, 50);
    lv_obj_set_x(ui_Channel3, 105);
    lv_obj_set_y(ui_Channel3, 18);
    lv_obj_clear_flag(ui_Channel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCh3 = lv_label_create(ui_Channel3);
    lv_obj_set_width(ui_LabelCh3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCh3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCh3, 0);
    lv_obj_set_y(ui_LabelCh3, -10);
    lv_obj_set_align(ui_LabelCh3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCh3, "Ch.3");

    ui_Channel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Channel4, 50);
    lv_obj_set_height(ui_Channel4, 50);
    lv_obj_set_x(ui_Channel4, 5);
    lv_obj_set_y(ui_Channel4, 68);
    lv_obj_clear_flag(ui_Channel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCh4 = lv_label_create(ui_Channel4);
    lv_obj_set_width(ui_LabelCh4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCh4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCh4, 0);
    lv_obj_set_y(ui_LabelCh4, -10);
    lv_obj_set_align(ui_LabelCh4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCh4, "Ch.4");

    ui_Channel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Channel5, 50);
    lv_obj_set_height(ui_Channel5, 50);
    lv_obj_set_x(ui_Channel5, 55);
    lv_obj_set_y(ui_Channel5, 68);
    lv_obj_clear_flag(ui_Channel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCh5 = lv_label_create(ui_Channel5);
    lv_obj_set_width(ui_LabelCh5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCh5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCh5, 0);
    lv_obj_set_y(ui_LabelCh5, -10);
    lv_obj_set_align(ui_LabelCh5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCh5, "Ch.5");

    ui_Channel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Channel6, 50);
    lv_obj_set_height(ui_Channel6, 50);
    lv_obj_set_x(ui_Channel6, 105);
    lv_obj_set_y(ui_Channel6, 68);
    lv_obj_clear_flag(ui_Channel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCh6 = lv_label_create(ui_Channel6);
    lv_obj_set_width(ui_LabelCh6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCh6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCh6, 0);
    lv_obj_set_y(ui_LabelCh6, -10);
    lv_obj_set_align(ui_LabelCh6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCh6, "Ch.6");

    ui_Volume = lv_slider_create(ui_Screen1);
    lv_slider_set_mode(ui_Volume, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_Volume, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Volume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Volume, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Volume, 90);
    lv_obj_set_height(ui_Volume, 3);
    lv_obj_set_x(ui_Volume, 60);
    lv_obj_set_y(ui_Volume, 7);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -52);
    lv_obj_set_y(ui_Label5, -56);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Volume");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Channel1 = NULL;
    ui_LabelCh1 = NULL;
    ui_Channel2 = NULL;
    ui_LabelCh2 = NULL;
    ui_Channel3 = NULL;
    ui_LabelCh3 = NULL;
    ui_Channel4 = NULL;
    ui_LabelCh4 = NULL;
    ui_Channel5 = NULL;
    ui_LabelCh5 = NULL;
    ui_Channel6 = NULL;
    ui_LabelCh6 = NULL;
    ui_Volume = NULL;
    ui_Label5 = NULL;

}
