// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Channel1;
extern lv_obj_t * ui_LabelCh1;
extern lv_obj_t * ui_Channel2;
extern lv_obj_t * ui_LabelCh2;
extern lv_obj_t * ui_Channel3;
extern lv_obj_t * ui_LabelCh3;
extern lv_obj_t * ui_Channel4;
extern lv_obj_t * ui_LabelCh4;
extern lv_obj_t * ui_Channel5;
extern lv_obj_t * ui_LabelCh5;
extern lv_obj_t * ui_Channel6;
extern lv_obj_t * ui_LabelCh6;
extern lv_obj_t * ui_Volume;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

